spring.application.name=sg-rsc-backend
springdoc.swagger-ui.path=/swagger-ui.html

spring.datasource.url=jdbc:postgresql://localhost:5432/sgrsc
spring.datasource.username=sgrsc
spring.datasource.password=sgrsc
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.flyway.enabled=true
