spring.application.name=sg-rsc-backend
springdoc.swagger-ui.path=/swagger-ui.html

spring.datasource.url=jdbc:postgresql://localhost:5432/sgrsc
spring.datasource.username=sgrsc
spring.datasource.password=sgrsc
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.flyway.enabled=true

# Keycloak / OAuth2 Resource Server
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8081/realms/sg-rsc

# MinIO
minio.endpoint=http://localhost:9000
minio.access-key=sgrsc
minio.secret-key=sgrsc123
minio.bucket=sg-rsc-documentos

# Logs para diagnóstico do Spring Security
logging.level.org.springframework.security=TRACE
logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.security=TRACE
logging.level.org.springframework.security.web.FilterChainProxy=TRACE